{"name": "Ручка /api/v1/courier/login", "status": "passed", "description": "Логинимся с неправильным логином, ожидаем ошибку 404 и сообщение 'Учетная запись не найдена'", "steps": [{"name": "Запрос на авторизацию с неправильным логином", "status": "passed", "start": 1743104317945, "stop": 1743104318258}, {"name": "Проверки на статус и ответ", "status": "passed", "start": 1743104318258, "stop": 1743104318258}], "start": 1743104317945, "stop": 1743104318259, "uuid": "25c45078-aae8-4573-b034-23736d411008", "historyId": "5ae90ce696050e993d40a8b921dd9749", "testCaseId": "5ae90ce696050e993d40a8b921dd9749", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_wrong_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-L3FF6PO"}, {"name": "thread", "value": "20604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}